#!/bin/bash
set -e

MARIADB_WORDPRESS_NAME=$(cat /run/secrets/mariadb_wordpress_name)
MARIADB_WORDPRESS_USER=$(cat /run/secrets/mariadb_wordpress_user)
MARIADB_WORDPRESS_PASSWORD=$(cat /run/secrets/mariadb_wordpress_password)

mysql -u root <<-EOSQL
CREATE DATABASE IF NOT EXISTS \`$MARIADB_WORDPRESS_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$MARIADB_WORDPRESS_USER'@'%' IDENTIFIED BY '$MARIADB_WORDPRESS_PASSWORD';
GRANT ALL PRIVILEGES ON \`$MARIADB_WORDPRESS_NAME\`.* TO '$MARIADB_WORDPRESS_USER'@'%';
FLUSH PRIVILEGES;
EOSQL
